In [1]:
# coding: utf-8
# наше всё
import numpy as np
import pandas as pd

#настройки pandas, с которыми лучше почти всегда
pd.set_option('display.max_rows', 45000)
pd.set_option('display.max_columns', 50000)
pd.set_option('display.max_colwidth', 5000)

import datetime as dt
from datetime import timedelta
from datetime import datetime
from dateutil.relativedelta import relativedelta

import seaborn as sns
import matplotlib.pyplot as plt

import json

import sys                                                                                                                                          

sys.path.append('/home/roman/python/footbal/sport/')
                                                                        
import data_load as dl

my_yaml = '/home/roman/python/kotelok/ab_game/secrets.yaml'

/home/roman/.local/lib/python3.10/site-packages/google/api_core/_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.12) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

In [14]:
dl.get_data(
    """
    select *
    from ab_game.users

    
    """,
    my_yaml,
    'ab_prod'
)

Started at  2026-08-03 10:43:12.871336
Finished at 2026-08-03 10:43:12.952599
Total process time 0:00:00.081263
Ready: 5 rows loaded

,user_id,internal_user_id,external_user_id,user_name,registration_date,registration_channel,last_active_at,is_paid,is_trial,is_active
0,a39bbb1e1cfba96588bec1072c7355343231622d88c0048200c4f0df2f71dee9,1,c8d730c7-33ef-4603-8d31-133257204ee4,Роман,2026-08-03 09:49:44.834726,streamlit,2026-08-03 09:56:40.821879,False,False,True
1,3ab4f77d9e5cded348e1a75e0115238c3cb376aac8873f4b467f0dee77cd7f79,2,c7bcf3e5-5c90-420a-a6d8-9bb45cea6925,Эля,2026-08-03 09:59:09.319600,streamlit,2026-08-03 10:05:22.353166,False,False,True
2,e0b98e48d9578da729ec6e9384f3b8528e652bdf8a0464c2e7d070619495ee27,3,96fbf5aa-f510-4bee-92d7-69c9336d8a06,Эля,2026-08-03 10:12:09.477425,streamlit,2026-08-03 10:17:53.600496,False,False,True
3,39d3ba5c6455eb99f6bcc641be32db01d9a9f52572c551b24b2658d41205176c,4,d8a21175-d117-4ae6-b9a6-389df044cba9,,2026-08-03 10:31:59.859431,streamlit,2026-08-03 10:31:59.893464,False,False,True
4,b88ca23e22da5fd3eed98cfa85e3e20a3a1e63b3ba58a0e2612c843932f6041f,5,7c9fdd94-913a-4acc-a12d-80fdfbdb339b,,2026-08-03 10:43:01.217666,streamlit,2026-08-03 10:43:01.280024,False,False,True

In [13]:
dl.get_data(
    """
    select *
    from ab_game.events
    where internal_user_id = 4

    order by timestamp

    
    """,
    my_yaml,
    'ab_prod'
)

Started at  2026-08-03 10:41:36.447559
Finished at 2026-08-03 10:41:36.608607
Total process time 0:00:00.161048
Ready: 1 rows loaded

,id,timestamp,user_id,internal_user_id,external_user_id,event_name,channel,event_parameters,inserted_at
0,345,2026-08-03 10:31:59.913449,39d3ba5c6455eb99f6bcc641be32db01d9a9f52572c551b24b2658d41205176c,4,d8a21175-d117-4ae6-b9a6-389df044cba9,start_screen_visit,streamlit,None,2026-08-03 10:31:59.921034